---
title: <span style="color:#686868"> **Coeficientes y Varianza**</span>
author: "Métodos y Simulación Estadística"
output:
  html_document:
    code_folding: hide
    css: style.css
---

En esta sección se muestra cómo construir **intervalos de confianza** para los parámetros \( \beta \) y \( \sigma^2 \) de un modelo de regresión lineal.


</br></br>
<div class="caja-ejemplo">
<h3>Ejemplo:</h3>
<p>

En este ejemplo, se continua con el **modelo de regresión lineal simple** para analizar la relación entre la **Resistencia de una soldadura (psi)** y la **Edad de la soldadura (semanas)**. El modelo resultante es el siguiente: 

\[
\widehat{\text{Resistencia}}_i \sim N(\hat{\mu}_i, \hat{\sigma}^2)
\]
\[
\hat{\mu}_i = \hat{\beta}_0 + \hat{\beta}_1 \times \text{Edad}_i
\]
\[
\hat{\mu}_i = 2627.82 - 37.15 \times \text{Edad}_i\\
\hat{\sigma} = 96.11
\]

El objetivo es construir un **intervalo de confianza del 95%** para el parámetro \( \beta_1 \) y para el parámetro \( \sigma^2 \).

---

Los códigos para determinar los IC del 95% para ambos parámetros son los siguientes:

<pre>
# Definir la URL del archivo con los datos
file <- "https://raw.githubusercontent.com/smramirezb/datos_ejemplos/refs/heads/main/dat_reg1.txt"

# Cargar el conjunto de datos desde la URL y almacenarlo en un dataframe
datos <- read.table(file = file, header = TRUE)

# Ajustar un modelo de regresión lineal simple con la variable Edad como predictor
mod1 <- lm(Resistencia ~ Edad, data = datos)

# Obtener el intervalo de confianza del 95% para el coeficiente de la variable Edad
confint(object = mod1, parm = "Edad", level = 0.95)

# Verificar si la librería "remotes" está instalada, si no, instalarla
if (!require("remotes")) install.packages("remotes")

# Instalar la librería "model" desde GitHub, si no está instalada
remotes::install_github("fhernanb/model")

# Cargar la librería "model" para calcular el intervalo de confianza para sigma^2
library(model)

# Obtener el intervalo de confianza del 95% para la varianza de los errores (sigma^2)
confint_sigma2(object = mod1, level = 0.95)
</pre>



```{r,eval=FALSE,warning=FALSE,message=FALSE}
# Definir la URL del archivo con los datos
file <- "https://raw.githubusercontent.com/smramirezb/datos_ejemplos/refs/heads/main/dat_reg1.txt"

# Cargar el conjunto de datos desde la URL y almacenarlo en un dataframe
datos <- read.table(file = file, header = TRUE)

# Ajustar un modelo de regresión lineal simple con la variable Edad como predictor
mod1 <- lm(Resistencia ~ Edad, data = datos)

# Obtener el intervalo de confianza del 95% para el coeficiente de la variable Edad
confint(object = mod1, parm = "Edad", level = 0.95)

# Verificar si la librería "remotes" está instalada, si no, instalarla
if (!require("remotes")) install.packages("remotes")

# Instalar la librería "model" desde GitHub, si no está instalada
remotes::install_github("fhernanb/model")

# Cargar la librería "model" para calcular el intervalo de confianza para sigma^2
library(model)

# Obtener el intervalo de confianza del 95% para la varianza de los errores (sigma^2)
confint_sigma2(object = mod1, level = 0.95)

```



Los **intervalos de confianza del 95%** para los parámetros del modelo de regresión son los siguientes:

- **Para el coeficiente \( \beta_1 \) (pendiente de la regresión):**
  
  \[
  IC_{95\%}(\beta_1) = (-43.223, -31.084)
  \]

  El intervalo **no incluye el cero**,  la variable **Edad** tiene un efecto significativo en la predicción de la resistencia.

  <pre>
  2.5 %   97.5 %
  Edad -43.22338 -31.0838
  </pre>

- **Para la varianza de los errores \( \sigma^2 \):**
  
  \[
  IC_{95\%}(\sigma^2) = (5273.516, 20199.24)
  \]

  Este intervalo representa la incertidumbre en la estimación de la **varianza de los errores del modelo**.

  <pre>
  2.5 %   97.5 %
  Sigma2 5273.516 20199.24
  </pre>

Estos resultados confirman la significancia de la variable **Edad** en la predicción de la **Resistencia** y proporcionan una estimación  de la variabilidad en los errores del modelo.


</p>
</div>